/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;


class StringUtilsTest {

    @Test
    public void isPositiveNumberShouldReturnTrue() {
        String testNumber = "21.0";
        boolean expected = StringUtils.isPositiveNumber(testNumber);
        Assertions.assertTrue(expected);
    }
}
